### ISSUE TITLE
Como posso ajudar?

### ISSUE THREAD

**Issue by denis-or** [appliedepi/epirhandbook_pt#18]
Oi pessoal. Como estão? 

Sou o Denis, aluno de doutorado em Epidemiologia da Escola Nacional de Saúde Pública, e tenho conhecimento nas áreas abordadas pelo epirhandbook. Gostaria de contribuir com o projeto. 

Estou a disposição para conversar.

Abraços.

**Comment by halian-vilela** [comment]
Opa! Fala @denis-or blz?

Foi mal a demora gigante na resposta!

O livro tava na parte final de revisão técnica pelo pessoal lá da matriz, eles tavam ajustando alguns bugs que estavam fora de nossa alçada e por isso ficamos um tempo sem voltar aqui no repositório. Eu tinha visto sua mensagem, não consegui responder no dia e depois esqueci! 👎 

Mas seguinte, o livro já está online no domínio oficial ( https://www.epirhandbook.com/pt/ ) mas esse repositório vai continuar sendo atualizado, então a melhor forma de colaborar é ler o livro e apontar ajustes seja no conteúdo real (que talvez valha a pena até mandar pro original em inglês) quanto na tradução (aí inclui termos mais precisos, erros de digitação, ortografia, etc)

Tudo certo? Por enquanto é isso!

Abraços, até mais!
